config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "shelters#index"
  resources :pets, except: %i[new create]

  resources :shelters do
    resources :pets, only: %i[index new create]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
# frozen_string_literal: true

class Pet < ApplicationRecord
  belongs_to :shelter, counter_cache: true
  before_save :make_not_adoptable, if: :shelter

  attribute :adoptable, :boolean, default: true
  attribute :age, :integer, default: 0

  validates :name, :breed, presence: true
  validates :age, numericality: { only_integer: true }

  scope :age_older_than, ->(age) { columns_for_index.where("age > ?", age) }

  def self.columns_for_index
    joins(:shelter).select(:id, :name, :breed, :age, :shelter_id, "shelters.name AS shelter_name")
  end

  def self.filter_by_name(name, exact)
    if exact
      columns_for_index.where("LOWER(pets.name) = ?", name.downcase)
    else
      columns_for_index.where("LOWER(pets.name) ~* ?", name.downcase)
    end
  end

  private

  def make_not_adoptable
    self.adoptable = false
  end
end

app/models/shelter.rb
# frozen_string_literal: true

class Shelter < ApplicationRecord
  has_many :pets, dependent: :destroy

  validates :name, :rank, :city, presence: true
  validates :rank, numericality: { only_integer: true }

  scope :columns_for_index, -> { select(:id, :name, :created_at, :pets_count) }
  scope :all_descending, -> { columns_for_index.order(created_at: :desc) }
  scope :sort_by_pets_count, ->(sort_type) { columns_for_index.order(pets_count: sort_type) }

  def self.filter_by_name(name, exact)
    if exact
      columns_for_index.where("LOWER(name) = ?", name.downcase)
    else
      columns_for_index.where("LOWER(name) ~* ?", name.downcase)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
# frozen_string_literal: true

class PetsController < ApplicationController
  before_action :select_pet, except: %i[index new create]
  before_action :select_shelter, if: -> { params[:shelter_id].present? }
  before_action :select_shelter_pets, if: -> { @shelter }

  def index
    if params[:shelter_id].present?
      apply_filters
      render "shelters/show"
    elsif params[:name].present?
      filter_by_name
    else
      @pets = Pet.columns_for_index
    end
  end

  def show; end

  def new
    @pet = @pets.new
  end

  def create
    @pets.create(pet_params)
    redirect_to shelter_pets_url, notice: "New pet is created."
  end

  def edit; end

  def update
    @pet.update!(pet_params)
    redirect_to pet_url(@pet), notice: "Pet has successfully updated."
  end

  def destroy
    @pet.destroy
    redirect_to pets_url, notice: "Pet has successfully deleted."
  end

  private

  def apply_filters
    apply_sort_filter
    apply_age_filter
  end

  def select_shelter
    @shelter = Shelter.includes(:pets).find(params[:shelter_id])
  end

  def select_pet
    @pet = Pet.columns_for_index.find(params[:id])
  end

  def select_shelter_pets
    @pets = @shelter.pets
  end

  def apply_sort_filter
    @pets = @pets.order(:name) if params[:sorted]
  end

  def apply_age_filter
    age_filter = params[:age_filter]
    @pets = @pets.age_older_than(age_filter.to_i) if age_filter
  end

  def filter_by_name
    @pets = Pet.filter_by_name(params[:name].strip, params[:exact])
  end

  def pet_params
    params.require(:pet).permit(:name, :breed, :age, :shelter_id)
  end
end

app/controllers/shelters_controller.rb
# frozen_string_literal: true

class SheltersController < ApplicationController
  before_action :select_shelter, except: %i[index new create]

  def index
    @shelters = if params[:sort].present?
                  sort_by_pets_count
                elsif params[:name].present?
                  filter_by_name
                else
                  Shelter.all_descending
                end
  end

  def show; end

  def new
    @shelter = Shelter.new
  end

  def create
    @shelter = Shelter.new(shelter_params)
    if @shelter.save
      redirect_to shelters_url, notice: "Shelter has been created."
    else
      render :new, notice: "There are some problems..."
    end
  end

  def edit; end

  def update
    if @shelter.update(shelter_params)
      redirect_to shelter_url(@shelter), notice: "Shelter has been updated."
    else
      render :edit, notice: "There are some problems..."
    end
  end

  def destroy
    @shelter.destroy
    redirect_to shelters_url, notice: "Shelter has been deleted."
  end

  private

  def filter_by_name
    Shelter.filter_by_name(params[:name].strip, params[:exact])
  end

  def sort_by_pets_count
    Shelter.sort_by_pets_count(params[:sort].strip)
  end

  def select_shelter
    @shelter = Shelter.find(params[:id])
  end

  def shelter_params
    params.require(:shelter).permit(:name, :rank, :city)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Shelters 4 Pets</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="container">
  <header>
    <h1 class="logo">
      <%= link_to "Shelters 4 Pets", root_path %>
    </h1>
    <nav class="links absolute b-0 right-0 m-t-8">
      <%= link_to "Shelters", shelters_path %>
      <%= link_to "Pets", pets_path %>
    </nav>
  </header>
  <main>
    <%= yield %>
  </main>
</div>
</body>
</html>

app/views/pets/_filter_form.html.erb
<div class="horizontal filter-form line-form">
  <span class="text-sm">Filters: </span>
  <%= form_with url: request.path, method: :get, local: true do |form| %>
    <%= form.label :age_filter, "age greater than: " %>
    <%= form.text_field :age_filter, value: (params[:age_filter] || 0), min: 0 %>
    <%= button_tag class: "btn-md btn-white" do %>
      <span class="icon-filter"></span>
    <% end %>
  <% end %>
  <%= button_to request.path, id:"sorted", class: "btn-md btn-white", params: { sorted: true }, method: :get do %>
    <span class="icon-sort-name-up"></span>
  <% end %>
</div>

app/views/pets/_form.html.erb
<% @form_model = local_assigns.dig(:locals, :form_objects) || @pet %>
<%= form_with model: @form_model, class:"record-form" do |form| %>
  <div class="form-field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="form-field">
    <%= form.label :breed %>
    <%= form.text_field :breed %>
  </div>
  <div class="form-field">
    <%= form.label :age %>
    <%= form.text_field :age %>
  </div>
  <div class="form-field">
    <%= form.submit %>
  </div>
<% end %>

app/views/pets/_pet.html.erb
<li class="pet">
  <%= link_to pet_path(pet) do %>
    <div class="details">
      <p><span>Name:</span><%= pet.name %></p>
      <p><span>Breed:</span><%= pet.breed %></p>
      <p><span>Age:</span><%= pet.age %></p>
      <% unless local_assigns.dig(:local, :hide_owner) %>
        <p>
          <span>Shelter:</span>
          <%= pet.shelter_name %>
        </p>
      <% end %>
    </div>
  <% end %>
</li>

app/views/pets/edit.html.erb
<h2>Edit Pet</h2>
<div class="section-top">
  <%= render "form" %>
</div>

app/views/pets/index.html.erb
<h2>All Pets</h2>
<div class="section-top">
  <div class="filters">
    <%= form_with url: request.path, method: :get, class: "vertical filter-form" do |form| %>
      <label for="name" class=" header">Filter by name</label>
      <%= form.text_field :name, value: params[:name] %>
      <label for="exact">
        <%= check_box_tag(:exact, "true", (params.key?(:exact))) %>
        Exact match
      </label>
      <%= button_tag class: "filter-button btn-white" do %>
        <span class="icon-filter">Filter</span>
      <% end %>
    <% end %>
  </div>
</div>

<ul class="pets">
  <%= render @pets %>
</ul>

app/views/pets/new.html.erb
<h2>New Pet</h2>
<div class="section-top">
  <%= render "form", locals: { form_objects: [@shelter, @pet] } %>
</div>

app/views/pets/show.html.erb
<h2>Pet Details: <%= @pet.name.upcase %></h2>
<div class="section-top pet-details">
  <p><span>Breed:</span><%= @pet.breed %></p>
  <p><span>Age:</span><%= @pet.age %></p>
  <p>
    <span>
    Shelter:
    </span><%= link_to @pet.shelter_name, shelter_path(@pet.shelter) %>
  </p>
  <p class="links">
    <%= link_to "Edit", edit_pet_path(@pet), class: "btn-md hover-blue" %>
    <%= link_to "Delete", pet_path(@pet), class: "btn-md hover-red", method: :delete, data: { confirm: "Are you sure?" } %>
  </p>
</div>

app/views/shelters/_form.html.erb
<%= form_with model: @shelter, class:"record-form" do |form| %>
  <div class="form-field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="form-field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>
  <div class="form-field">
    <%= form.label :rank %>
    <%= form.text_field :rank %>
  </div>
  <div class="form-field">
    <%= form.submit %>
  </div>
<% end %>

app/views/shelters/_shelter.html.erb
<li class="shelter">
  <%= link_to shelter_path(shelter) do %>
      <h2><%= shelter.name %></h2>
    <div class="details">
      <p><%= shelter.pets_count %> pets</p>
      <p>
        <span class="text-gray-500"><em>created</em>
          <%= "#{time_ago_in_words(shelter.created_at)} ago" %>
      </span>
      </p>
    </div>
  <% end %>
  <div class="action-links">
    <%= link_to "Edit", edit_shelter_path(shelter) %>
    <%= link_to "Delete", shelter_path(shelter), method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
</li>

app/views/shelters/edit.html.erb
<h2>Edit Shelter</h2>
<div class="section-top">
  <%= render "form" %>
</div>

app/views/shelters/index.html.erb
<h2>All Shelters</h2>
<div class="section-top">
  <div class="filters">
    <%= form_with url: request.path, method: :get, class: "vertical filter-form" do |form| %>
        <label for="name" class=" header">Filter by name</label>
        <%= form.text_field :name, value: params[:name] %>
        <label for="exact">
          <%= check_box_tag(:exact, "true", (params.key?(:exact))) %>
          Exact match
        </label>
        <%= button_tag class: "filter-button btn-white" do %>
          <span class="icon-filter">Filter</span>
        <% end %>
    <% end %>
    <div class="horizontal filter-form">
      <span class="text-sm">Sort by pets count: </span>
      <%= button_to request.path, id:"sort-asc", class: "filter-button btn-white", params: { sort: "asc" }, method: :get do %>
        <span class="icon-sort-name-up"></span>
      <% end %>
      <%= button_to request.path, id:"sort-desc", class: "filter-button btn-white", params: { sort: "desc" }, method: :get do %>
        <span class="icon-sort-name-down"></span>
      <% end %>
    </div>
  </div>
  <div class="buttons">
    <%= link_to new_shelter_path, class: "link-as-button btn-white" do %>
      <span class="icon-plus">New Shelter</span>
    <% end %>
  </div>
</div>

<ul class="shelters">
  <%= render @shelters %>
</ul>

app/views/shelters/new.html.erb
<h2>New Shelter</h2>
<div class="section-top">
<%= render "form" %>
</div>

app/views/shelters/show.html.erb
<h2>Shelter Details: <%= @shelter.name.upcase %></h2>
<div class="section-top shelter-details">
  <p class="justify-right">
    <%= link_to "Edit", edit_shelter_path(@shelter), class: "btn-md hover-blue" %>
    <%= link_to "Delete", shelter_path(@shelter),
                class: "btn-md hover-red", method: :delete, data: { confirm: "Are you sure?" } %>
  </p>
<div class="-mt-40">
  <p><span>City:</span> <%= @shelter.city %></p>
  <p><span>Rank:</span> <%= @shelter.rank %></p>
  <p><span>Pets Count:</span> <%= @shelter.pets.size %></p>

</div>

  <p>
    <%= link_to "Show Pets", shelter_pets_path(@shelter), class: "btn-lg hover-yellow" %>
    <%= link_to "New Pet", new_shelter_pet_path(@shelter), class: "btn-lg hover-blue" %>
  </p>

  <% if @pets %>
    <h3>Pets under <%= @shelter.name %></h3>
    <%= render "filter_form" %>
    <ul class="pets">
      <%= render @pets, local: { hide_owner: true } %>
    </ul>
  <% end %>
</div>